[workspace]
authors = ["tdinapoli <tomas.dina98@gmail.com>"]
channels = ["conda-forge"]
name = "measurement_script"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
python = "3.12.*"
pycct = { path = "../pycct" }
numpy = ">=2.3.5,<3"
